name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/moonmodules/WLED/archive/refs/heads/mdev.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        npm install
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32dev' >>platformio.ini
        echo 'build_flags = ${env:esp32dev.build_flags} ${common.debug_flags} -D SR_DEBUG -D MIC_LOGGER -D WLED_DISABLE_ESPNOW -D WLED_DISABLE_BROWNOUT_DET -D WLED_DEBUG -D WLED_DEBUG_HOST='\''"192.168.86.178"'\'' -D WLED_DEBUG_PORT=7868 -D WLED_DEBUG_NTP -D WLED_DEBUG_IMPROV -D WLED_ENABLE_MQTT -D WLED_DISABLE_LOXONE -D WLED_ENABLE_ADALIGHT -D WLED_ENABLE_PIXART -D WLED_DISABLE_ALEXA -D WLED_DISABLE_HUESYNC -D LEDPIN=23 -D I2S_SDPIN=0 -D I2S_WSPIN=0 -D I2S_CKPIN=0 -D WLED_MAX_USERMODS=6 -D WLED_MAX_BUSSES=6 -D DEFAULT_LED_COUNT=142 -D DEFAULT_LED_TYPE=TYPE_APA102 -D DEFAULT_LED_COLOR_ORDER=COL_ORDER_BGR -D MAX_LEDS=8192 -D CLIENT_SSID='\''"monsterhoneybun"'\'' -D CLIENT_PASS='\''"zuhbah5pirqociFhiv"'\'' -D WLED_AP_SSID='\''"WLED-FUKED"'\'' -D WLED_AP_PASS='\''"fuckme69"'\'' -D USERMOD_FOUR_LINE_DISPLAY -D USERMOD_ROTARY_ENCODER_UI -D USE_ALT_DISPlAY -D USERMOD_PWM_OUTPUTS -D USERMOD_SSDR' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32dev.lib_deps}' >>platformio.ini
        echo '  olikraus/U8g2 @ ^2.28.8' >>platformio.ini
        echo '  olikraus/U8g2 @ ^2.28.8' >>platformio.ini
        echo '  Wire' >>platformio.ini
        
        echo 'build_unflags= -D WLED_RELEASE_NAME' >>platformio.ini
        pio run -e custom_build || pio run -e custom_build
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
