[env:custom_build]
extends = env:esp32_4MB_S
build_flags = ${env:esp32_4MB_S.build_flags} -D USERMOD_DHT -D USERMOD_DHT_CELSIUS -D USERMOD_AUTO_SAVE -D USERMOD_FOUR_LINE_DISPLAY -D USERMOD_ROTARY_ENCODER_UI -D USERMOD_MODE_SORT -D USERMOD_SENSORSTOMQTT -D RGB_ROTARY_ENCODER
lib_deps = 
  ${env:esp32_4MB_S.lib_deps}
  https://github.com/alwynallan/DHT_nonblocking
  olikraus/U8g2 @ ^2.28.8
  olikraus/U8g2 @ ^2.28.8
  Wire
  adafruit/Adafruit BMP280 Library @ 2.1.0
  adafruit/Adafruit CCS811 Library @ 1.0.4
  adafruit/Adafruit Si7021 Library @ 1.4.0
  adafruit/Adafruit Unified Sensor
  lennarthennigs/ESP Rotary@^1.5.0
